release:
  name_template: "{{ .ProjectName }} v{{ .Version }}"

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - main: ./cmd/flussonic_exporter
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64

archives:
  - format: binary
    name_template: '{{ .Binary }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}'

dockers:
  - goos: linux
    goarch: amd64
    image_templates:
      - "sputnik-systems/flussonic-exporter:latest"
      - "sputnik-systems/flussonic-exporter:{{ .Tag }}"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
