release:
  name_template: "{{ .ProjectName }} {{ .Tag }}"

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - main: ./cmd/flussonic_exporter
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64

archives:
  - format: binary
    name_template: '{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
